# Generated by Django 5.2.1 on 2025-05-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_booking_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
    ]
