# Generated by Django 5.2.1 on 2025-05-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_alter_hotel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Картой'), ('CASH', 'Наличными')], default='CARD', max_length=5, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SGL', 'Одноместный'), ('DBL', 'Двухместный'), ('FAM', 'Семейный'), ('LUX', 'Люкс')], max_length=3),
        ),
    ]
