# Generated by Django 5.2.1 on 2025-05-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_alter_payment_payment_method_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SGL', 'Одноместный'), ('DBL', 'Двухместный'), ('FAM', 'Семейный'), ('LUX', 'Люкс')], max_length=3, verbose_name='Тип номера'),
        ),
    ]
