# Generated by Django 5.2.1 on 2025-05-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_alter_review_rating_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='host.hotel', verbose_name='Отель'),
        ),
    ]
