# Generated by Django 5.2.1 on 2025-05-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_alter_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='Рейтинг'),
        ),
    ]
