# Generated by Django 5.0.6 on 2025-05-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Удобства'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name'], 'verbose_name': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='hotelservice',
            options={'verbose_name': 'Услуги отеля'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номера'},
        ),
    ]
