# Generated by Django 5.2.1 on 2025-05-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0008_alter_amenity_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name'], 'verbose_name': 'Отели', 'verbose_name_plural': 'Отели'},
        ),
    ]
