# Generated by Django 5.2.1 on 2025-05-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_alter_amenity_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='hotels', through='host.HotelAmenity', to='host.amenity', verbose_name='Удобства'),
        ),
    ]
