# Generated by Django 5.2.1 on 2025-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0011_hotel_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_pdf',
            field=models.FileField(blank=True, help_text='PDF файл с подтверждением бронирования', null=True, upload_to='booking_confirmations/%Y/%m/%d/', verbose_name='PDF подтверждение'),
        ),
    ]
