# Generated by Django 5.2.1 on 2025-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0011_hotel_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('exam_date', models.DateField(verbose_name='Дата проведения экзамена')),
                ('image', models.ImageField(upload_to='exams/', verbose_name='Задание (изображение)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('users', models.ManyToManyField(to='host.user', verbose_name='Пользователи, сдающие экзамен')),
            ],
        ),
    ]
