# Generated by Django 5.2.1 on 2025-06-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0012_booking_confirmation_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='booking_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на страницу бронирования', null=True, verbose_name='Ссылка на бронирование'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, help_text='Официальный сайт отеля', null=True, verbose_name='Веб-сайт'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='booking_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка для бронирования по акции', null=True, verbose_name='Ссылка на бронирование'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='details_url',
            field=models.URLField(blank=True, help_text='Ссылка на страницу с подробным описанием акции', null=True, verbose_name='Подробности акции'),
        ),
    ]
