# Generated by Django 5.2.1 on 2025-06-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0013_hotel_booking_url_hotel_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(db_collation='NOCASE', max_length=255, verbose_name='Местоположение'),
        ),
    ]
