# Generated by Django 5.2.1 on 2025-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0014_alter_hotel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(db_collation='NOCASE', db_index=True, max_length=255, verbose_name='Местоположение'),
        ),
    ]
